name: Build Compose App
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            gradle_task: ":composeApp:packageReleaseDeb"
            artifact_ext: deb
          - os: windows-latest
            gradle_task: ":composeApp:packageReleaseMsi"
            artifact_ext: msi
          - os: macos-latest
            gradle_task: ":composeApp:packageReleaseDmg"
            artifact_ext: dmg

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: ./gradlew ${{ matrix.gradle_task }}

      - name: Find version
        id: version
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Rename artifact with version
        shell: bash
        run: |
          mkdir artifacts
          FILE=$(find composeApp/build/compose/binaries -type f -name "*.${{ matrix.artifact_ext }}" | head -n 1)
          cp "$FILE" "artifacts/youtube-codes-${{ env.VERSION }}-${{ runner.os }}.${{ matrix.artifact_ext }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube-codes-${{ env.VERSION }}-${{ runner.os }}
          path: artifacts/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ./dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
